# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b93498ef6dce3aac482dc9b4f7755e785758f7eaa65483ea84132e616d5ee78b052b02f4e85e3b52372f4d3b30b787a1b9f2ca7e76d2b843e30144553c914c0f

test:
  secret_key_base: b20b6bf0a63187a1d75343bc161eae84d6d18d70d9c8abf744e36a959fea8a709fa99f548bdbe3265a9932a6d963875ca526d145d739bcdc28a74a78501bd16e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
